// ============================================================
// MidtermReviewData.js — content for the midterm review module
// Physical Chemistry 2 (물리화학 2) · Weeks 1–6
// SKKU School of Chemical Engineering · SPMDL · Prof. S. Joon Kwon
// ------------------------------------------------------------
// Every number in PRACTICE and PAST is reproduced by
// codes/python/midterm_review_check.py (shown in the "Check code" tab).
// ============================================================

export const WEEKS = [
  { w: 1, color: "#f59e0b", ko: "양자역학의 탄생", en: "Birth of Quantum Mechanics" },
  { w: 2, color: "#38bdf8", ko: "파동역학과 행렬역학", en: "Wave & Matrix Mechanics" },
  { w: 3, color: "#a78bfa", ko: "조화진동자와 각운동량", en: "Harmonic Oscillator & Angular Momentum" },
  { w: 4, color: "#34d399", ko: "수소 원자·스핀·기체 수송", en: "Hydrogen Atom, Spin & Gas Transport" },
  { w: 5, color: "#f472b6", ko: "분자간 힘과 액체", en: "Intermolecular Forces & Liquids" },
  { w: 6, color: "#a3e635", ko: "고분자·자기조립·반응속도론", en: "Macromolecules, Self-Assembly & Kinetics" },
];

// ── week map: one guiding question + three must-do skills per week ──
export const SKILLS = [
  {
    w: 1,
    ko: { q: "고전 물리는 왜 흑체복사를 설명하지 못했고, Planck는 무엇을 바꿨는가?",
      s: ["Planck 식에서 Wien 법칙·Stefan–Boltzmann 법칙·Rayleigh–Jeans 극한을 끌어낼 수 있다",
          "광자 에너지 E = hν = hc/λ로 광자 수·에너지를 계산할 수 있다",
          "L = T − U에서 Euler–Lagrange 방정식과 H = pq̇ − L을 구할 수 있다"] },
    en: { q: "Why could classical physics not explain blackbody radiation, and what did Planck change?",
      s: ["Get Wien's law, the Stefan–Boltzmann law and the Rayleigh–Jeans limit from Planck's law",
          "Count photons and their energies with E = hν = hc/λ",
          "Go from L = T − U to the Euler–Lagrange equation and to H = pq̇ − L"] },
  },
  {
    w: 2,
    ko: { q: "파동함수는 무엇을 알려 주고, 경계조건은 왜 에너지를 양자화하는가?",
      s: ["상자 속 입자의 ψₙ, Eₙ를 쓰고 구간 확률·기댓값을 적분으로 구할 수 있다",
          "de Broglie 파장과 불확정성 관계로 크기를 어림할 수 있다",
          "장벽 투과 확률이 폭과 높이에 지수적으로 민감함을 계산으로 보일 수 있다"] },
    en: { q: "What does a wavefunction tell us, and why do boundary conditions quantize energy?",
      s: ["Write ψₙ and Eₙ for a particle in a box and integrate for probabilities and expectation values",
          "Make order-of-magnitude estimates with the de Broglie wavelength and the uncertainty relation",
          "Show by calculation that tunnelling depends exponentially on barrier width and height"] },
  },
  {
    w: 3,
    ko: { q: "포물선 퍼텐셜과 회전은 왜 등간격·l(l+1) 같은 독특한 준위를 만드는가?",
      s: ["환산질량과 힘상수로 진동 파수·영점에너지를 계산할 수 있다",
          "â, â†로 ⟨x²⟩ 같은 기댓값을 적분 없이 구할 수 있다",
          "|L| = √(l(l+1))ℏ, L_z = mℏ, L±의 작용을 계산하고 벡터 모델로 해석할 수 있다"] },
    en: { q: "Why do a parabolic potential and rotation give such distinctive level patterns (equal spacing, l(l+1))?",
      s: ["Compute a vibrational wavenumber and zero-point energy from the force constant and reduced mass",
          "Use â and â† to get expectation values such as ⟨x²⟩ without integrals",
          "Work with |L| = √(l(l+1))ℏ, L_z = mℏ and L±, and read them with the vector model"] },
  },
  {
    w: 4,
    ko: { q: "수소 원자의 준위와 스핀은 스펙트럼과 주기율표를 어떻게 설명하고, 기체 분자는 얼마나 빨리 움직이는가?",
      s: ["두 준위 사이 전이의 파장·계열을 계산하고 축퇴도를 셀 수 있다",
          "Maxwell–Boltzmann 분포의 세 특성 속력을 구분해 계산할 수 있다",
          "평균자유행로·충돌 빈도를 압력과 온도에 따라 계산할 수 있다"] },
    en: { q: "How do hydrogen's levels and spin explain spectra and the periodic table, and how fast do gas molecules move?",
      s: ["Compute transition wavelengths and series, and count degeneracies",
          "Tell apart and compute the three characteristic speeds of the Maxwell–Boltzmann distribution",
          "Compute mean free paths and collision frequencies as functions of p and T"] },
  },
  {
    w: 5,
    ko: { q: "중성 분자는 왜 서로 끌어당기고, 그 힘이 표면과 모세관에서 어떻게 드러나는가?",
      s: ["Debye 식으로 쌍극자 모멘트와 편극성을 분리해 낼 수 있다",
          "Keesom·유도·London 힘의 r⁻⁶ 의존성과 Lennard-Jones 퍼텐셜을 다룰 수 있다",
          "Young–Laplace, 모세관 상승, Kelvin 식을 수치에 적용할 수 있다"] },
    en: { q: "Why do neutral molecules attract one another, and how does that show up at surfaces and in capillaries?",
      s: ["Separate the dipole moment and polarizability with the Debye equation",
          "Handle the r⁻⁶ Keesom, induction and London forces and the Lennard-Jones potential",
          "Apply the Young–Laplace, capillary-rise and Kelvin equations to numbers"] },
  },
  {
    w: 6,
    ko: { q: "고분자의 크기는 분자량과 어떻게 이어지고, 반응 속도는 농도·시간·온도와 어떻게 이어지는가?",
      s: ["Mn, Mw, Đ와 랜덤 코일의 크기 척도(R_c, R_rms, R_g)를 계산할 수 있다",
          "농도–시간 데이터에서 반응 차수와 속도 상수를 결정할 수 있다",
          "Arrhenius 식으로 활성화 에너지와 온도·촉매의 효과를 계산할 수 있다"] },
    en: { q: "How does polymer size follow from molar mass, and how do rates follow from concentration, time and temperature?",
      s: ["Compute Mn, Mw, Đ and the size measures of a random coil (R_c, R_rms, R_g)",
          "Determine reaction order and rate constant from concentration–time data",
          "Use the Arrhenius equation for activation energies and for the effect of temperature and catalysts"] },
  },
];

// ── key formulas ────────────────────────────────────────────
// eq: the formula; ko/en: what it means and when to use it
export const FORMULAS = [
  // Week 1
  { w: 1, eq: "E_λ = (2πhc²/λ⁵) · 1/(e^{hc/λk_BT} − 1)", ko: "Planck의 분광 방출능. 짧은 파장에서 지수 함수가 모드를 억눌러 자외선 파탄을 막는다.", en: "Planck's spectral emissive power. At short wavelengths the exponential suppresses the modes and removes the ultraviolet catastrophe." },
  { w: 1, eq: "λ_max · T = 2.898×10⁻³ m·K", ko: "Wien 변위 법칙. 온도가 두 배면 피크 파장은 절반.", en: "Wien's displacement law. Double the temperature and the peak wavelength halves." },
  { w: 1, eq: "E = σT⁴,  σ = 5.670×10⁻⁸ W m⁻² K⁻⁴", ko: "Stefan–Boltzmann 법칙. Planck 식을 모든 파장에 대해 적분한 결과.", en: "Stefan–Boltzmann law: Planck's law integrated over all wavelengths." },
  { w: 1, eq: "E_λ ≈ 2πck_BT/λ⁴   (hc/λk_BT ≪ 1)", ko: "Rayleigh–Jeans 극한. h가 사라지는 고전 극한이며 λ → 0에서 발산한다.", en: "Rayleigh–Jeans limit: the classical limit in which h drops out; it diverges as λ → 0." },
  { w: 1, eq: "⟨E⟩ = hν/(e^{hν/k_BT} − 1)  →  k_BT  (hν ≪ k_BT)", ko: "진동 모드 하나의 평균 에너지. 저주파에서만 등분배 k_BT를 회복한다.", en: "Mean energy of one oscillator mode; equipartition (k_BT) is recovered only at low frequency." },
  { w: 1, eq: "E = hν = hc/λ,   hc = 1239.84 eV·nm", ko: "광자 에너지. 파장(nm)을 eV로 바꿀 때 1239.84를 나누면 된다.", en: "Photon energy. Divide 1239.84 by the wavelength in nm to get eV." },
  { w: 1, eq: "d/dt(∂L/∂q̇) − ∂L/∂q = 0,   L = T − U", ko: "Euler–Lagrange 방정식. 작용 S = ∫L dt가 정류값을 갖는 경로가 실제 운동이다.", en: "Euler–Lagrange equation: the actual path makes the action S = ∫L dt stationary." },
  { w: 1, eq: "p = ∂L/∂q̇,  H = pq̇ − L,  q̇ = ∂H/∂p,  ṗ = −∂H/∂q", ko: "일반화 운동량과 Hamiltonian. L이 q를 포함하지 않으면 p가 보존된다.", en: "Generalized momentum and the Hamiltonian. If L does not contain q, p is conserved." },
  { w: 1, eq: "Ĥψ = Eψ,   p̂ = −iℏ ∂/∂x", ko: "Schrödinger 방정식은 고유값 문제다. 경계조건이 허용되는 E를 고른다.", en: "The Schrödinger equation is an eigenvalue problem; boundary conditions select the allowed E." },
  // Week 2
  { w: 2, eq: "λ = h/p", ko: "de Broglie 관계. 전위차 V로 가속된 전자는 p = √(2meV).", en: "de Broglie relation. An electron accelerated through V has p = √(2meV)." },
  { w: 2, eq: "Δx · Δp ≥ ℏ/2,   ΔA · ΔB ≥ ½|⟨[Â, B̂]⟩|", ko: "불확정성 관계. 교환하지 않는 두 관측량은 동시에 정확할 수 없다.", en: "Uncertainty relations: two observables that do not commute cannot both be sharp." },
  { w: 2, eq: "ψₙ = √(2/L) sin(nπx/L),   Eₙ = n²h²/8mL² = n²π²ℏ²/2mL²", ko: "상자 속 입자. n은 1부터, 마디는 n − 1개, 에너지는 L⁻²에 비례.", en: "Particle in a box. n starts at 1, ψₙ has n − 1 nodes and E scales as L⁻²." },
  { w: 2, eq: "P(a < x < b) = ∫ₐᵇ |ψ|² dx,   P(Eₙ) = |cₙ|²", ko: "Born 해석과 측정 공준. 중첩 상태에서 에너지를 재면 Eₙ이 확률 |cₙ|²로 나온다.", en: "Born interpretation and the measurement postulate: measuring E on a superposition gives Eₙ with probability |cₙ|²." },
  { w: 2, eq: "Ψ(x,t) = Σ cₙ ψₙ(x) e^{−iEₙt/ℏ}", ko: "시간 전개. 정상 상태 하나는 |Ψ|²가 변하지 않고, 서로 다른 Eₙ이 섞이면 맥놀이가 생긴다.", en: "Time evolution. A single stationary state has a constant |Ψ|²; mixing different Eₙ produces beats." },
  { w: 2, eq: "T ≈ 16(E/V)(1 − E/V) e^{−2κa},   κ = √(2m(V − E))/ℏ", ko: "넓은 장벽(κa ≫ 1)의 투과 확률. 폭 a가 두 배면 지수 인자는 제곱으로 작아진다.", en: "Transmission through a wide barrier (κa ≫ 1). Doubling a squares the exponential factor." },
  { w: 2, eq: "E = (n_x² + n_y² + n_z²) h²/8mL²", ko: "정육면체 상자. 양자수 조합이 달라도 제곱합이 같으면 축퇴.", en: "Cubic box. Different quantum-number sets with the same sum of squares are degenerate." },
  { w: 2, eq: "[x̂, p̂] = x̂p̂ − p̂x̂ = iℏ", ko: "정준 교환 관계. 행렬역학의 출발점이자 Δx·Δp ≥ ℏ/2의 근원.", en: "Canonical commutator: the starting point of matrix mechanics and the origin of Δx·Δp ≥ ℏ/2." },
  // Week 3
  { w: 3, eq: "E_v = (v + ½)ℏω,   ω = √(k/μ),   μ = m₁m₂/(m₁ + m₂)", ko: "조화진동자. 준위 간격이 일정하고 v = 0에도 영점에너지 ℏω/2가 남는다.", en: "Harmonic oscillator: equally spaced levels, and a zero-point energy ℏω/2 even at v = 0." },
  { w: 3, eq: "ν̃ = ω/2πc   (c = 2.998×10¹⁰ cm s⁻¹ → cm⁻¹)", ko: "진동 파수. 분광학에서 쓰는 단위는 cm⁻¹이므로 c를 cm/s로 넣는다.", en: "Vibrational wavenumber. Spectroscopists use cm⁻¹, so insert c in cm/s." },
  { w: 3, eq: "ψ_v = N_v H_v(y) e^{−y²/2},  y = √(mω/ℏ) x;  H₀ = 1, H₁ = 2y, H₂ = 4y² − 2", ko: "고유함수는 Hermite 다항식 × Gaussian. 고전 전환점 밖에도 확률이 있다.", en: "Eigenfunctions are Hermite polynomials times a Gaussian; there is probability beyond the classical turning points." },
  { w: 3, eq: "â|v⟩ = √v |v−1⟩,  â†|v⟩ = √(v+1) |v+1⟩,  [â, â†] = 1", ko: "사다리 연산자. 한 칸씩 내리고 올리며 계수가 √ 꼴로 붙는다.", en: "Ladder operators move one rung down or up, with √ coefficients." },
  { w: 3, eq: "x̂ = √(ℏ/2mω)(â + â†),   Ĥ = ℏω(â†â + ½)", ko: "x̂를 사다리 연산자로 쓰면 ⟨x⟩, ⟨x²⟩ 같은 기댓값이 적분 없이 나온다.", en: "Writing x̂ with ladder operators gives ⟨x⟩ and ⟨x²⟩ without integrals." },
  { w: 3, eq: "L̂²|l,m⟩ = ℏ² l(l+1)|l,m⟩,   L̂_z|l,m⟩ = mℏ|l,m⟩,   m = −l … l", ko: "각운동량 고유값. 크기는 √(l(l+1))ℏ로 lℏ보다 항상 크다.", en: "Angular-momentum eigenvalues. The magnitude √(l(l+1))ℏ is always larger than lℏ." },
  { w: 3, eq: "[L̂_x, L̂_y] = iℏL̂_z,   [L̂², L̂_z] = 0", ko: "L²과 L_z는 동시에 정할 수 있지만 L_x, L_y, L_z는 하나만 정할 수 있다.", en: "L² and L_z can be sharp together, but only one of L_x, L_y, L_z at a time." },
  { w: 3, eq: "L̂±|l,m⟩ = ℏ√((l ∓ m)(l ± m + 1)) |l, m±1⟩", ko: "각운동량 사다리 연산자. m = l에서 L̂₊를 걸면 0.", en: "Angular-momentum ladder operators; L̂₊ annihilates m = l." },
  { w: 3, eq: "cos θ = m/√(l(l+1))", ko: "벡터 모델에서 L과 z축 사이 각. m = l이어도 θ ≠ 0이다.", en: "Vector-model angle between L and the z axis; θ ≠ 0 even for m = l." },
  // Week 4
  { w: 4, eq: "Eₙ = −13.6 eV/n²,   l = 0 … n−1,   m_l = −l … l", ko: "수소 원자 준위와 양자수 규칙.", en: "Hydrogen energy levels and the quantum-number rules." },
  { w: 4, eq: "λ = 1239.84 eV·nm / ΔE,   1/λ = R_H(1/n₁² − 1/n₂²)", ko: "방출 파장. n₁ = 1 Lyman, 2 Balmer, 3 Paschen. R_H = 109 677 cm⁻¹.", en: "Emission wavelength. n₁ = 1 Lyman, 2 Balmer, 3 Paschen. R_H = 109 677 cm⁻¹." },
  { w: 4, eq: "축퇴도 g = n² (스핀 포함 2n²)", en_eq: "degeneracy g = n² (2n² with spin)", ko: "같은 n의 궤도 수. 스핀까지 세면 두 배.", en: "Number of orbitals with the same n; twice that with spin." },
  { w: 4, eq: "Ŝ² = s(s+1)ℏ² = ¾ℏ²,   Ŝ_z = ±ℏ/2,   Ŝ = (ℏ/2)σ̂", ko: "전자 스핀 ½. Stern–Gerlach 실험의 두 갈래가 그 증거.", en: "Electron spin ½; the two beams of the Stern–Gerlach experiment are the evidence." },
  { w: 4, eq: "ΔE = μ_B B m_l,   μ_B = 9.274×10⁻²⁴ J T⁻¹", ko: "정상 Zeeman 효과. 자기장이 m_l 축퇴를 푼다.", en: "Normal Zeeman effect: a magnetic field lifts the m_l degeneracy." },
  { w: 4, eq: "f(v) = 4π(M/2πRT)^{3/2} v² e^{−Mv²/2RT}", ko: "Maxwell–Boltzmann 속력 분포. v²(상태 수)와 Boltzmann 인자의 곱.", en: "Maxwell–Boltzmann speed distribution: v² (number of states) times the Boltzmann factor." },
  { w: 4, eq: "v_mp = √(2RT/M),  v̄ = √(8RT/πM),  v_rms = √(3RT/M)", ko: "세 특성 속력. 비는 1 : 1.128 : 1.225. M은 kg/mol.", en: "Three characteristic speeds in the ratio 1 : 1.128 : 1.225. M in kg/mol." },
  { w: 4, eq: "λ = k_BT/(√2 σp),   z = √2 σ v̄ p/k_BT", ko: "평균자유행로와 충돌 빈도. σ는 충돌 단면적(πd²).", en: "Mean free path and collision frequency; σ is the collision cross-section (πd²)." },
  { w: 4, eq: "D = ⅓λv̄,   κ = ⅓λv̄ C_V,m[A],   η = ⅓Mλv̄[A]", ko: "운동론의 수송 계수. 확산·열전도·점성이 같은 꼴.", en: "Kinetic-theory transport coefficients: diffusion, thermal conduction and viscosity share one form." },
  { w: 4, eq: "분출 속도 ∝ p/√(2πmk_BT)  →  rate ∝ 1/√M", en_eq: "effusion rate ∝ p/√(2πmk_BT)  →  rate ∝ 1/√M", ko: "Graham 법칙. 가벼운 기체가 더 빨리 빠져나간다.", en: "Graham's law: lighter gases effuse faster." },
  // Week 5
  { w: 5, eq: "μ = qR,   1 D = 3.336×10⁻³⁰ C·m,   μ_res = 2μ₁cos(θ/2)", ko: "쌍극자 모멘트와 벡터 합성.", en: "Dipole moment and vector addition." },
  { w: 5, eq: "P_m = (N_A/3ε₀)(α + μ²/3k_BT),   α′ = α/4πε₀", ko: "Debye 식. P_m을 1/T에 대해 그리면 기울기에서 μ, 절편에서 α.", en: "Debye equation. Plot P_m against 1/T: μ from the slope, α from the intercept." },
  { w: 5, eq: "V_Keesom = −2μ₁²μ₂²/[3(4πε₀)² k_BT r⁶]", ko: "회전하는 두 쌍극자의 평균 인력. 1/T에 비례.", en: "Average attraction of two rotating dipoles; it scales as 1/T." },
  { w: 5, eq: "V_ind = −μ₁²α₂′/(4πε₀ r⁶),   V_London = −(3/2)α₁′α₂′ I₁I₂/[(I₁ + I₂) r⁶]", ko: "유도 힘과 London 분산력. 무극성 분자도 서로 끌어당긴다.", en: "Induction and London dispersion; even nonpolar molecules attract." },
  { w: 5, eq: "V = 4ε[(r₀/r)¹² − (r₀/r)⁶],   r_min = 2^{1/6} r₀,   V(r_min) = −ε", ko: "Lennard-Jones 퍼텐셜. r₀에서 V = 0, 우물 깊이 ε.", en: "Lennard-Jones potential: V = 0 at r₀, well depth ε." },
  { w: 5, eq: "Δp = 2σ/r   (거품막은 두 면이라 4σ/r)", en_eq: "Δp = 2σ/r   (a soap film has two surfaces: 4σ/r)", ko: "Young–Laplace 식. 작은 방울일수록 안쪽 압력이 크다.", en: "Young–Laplace equation: the smaller the drop, the higher the inside pressure." },
  { w: 5, eq: "h = 2σ cos θ/(ρgr),   σ_sg = σ_sl + σ_lg cos θ", ko: "모세관 상승과 Young 식. θ < 90°면 올라가고 θ > 90°(수은)면 내려간다.", en: "Capillary rise and Young's equation: liquids with θ < 90° rise, mercury (θ > 90°) is depressed." },
  { w: 5, eq: "p = p* e^{2σV_m/rRT}", ko: "Kelvin 식. 작은 방울의 증기압이 커서 큰 방울이 작은 방울을 먹는다(Ostwald 숙성).", en: "Kelvin equation. Small drops have a higher vapour pressure, so large drops grow at their expense (Ostwald ripening)." },
  // Week 6
  { w: 6, eq: "M̄n = ΣNᵢMᵢ/ΣNᵢ,   M̄w = ΣNᵢMᵢ²/ΣNᵢMᵢ,   Đ = M̄w/M̄n", ko: "평균 분자량. Mn은 사슬 하나에 한 표, Mw는 질량에 한 표.", en: "Average molar masses: Mn gives each chain one vote, Mw gives each unit of mass one vote." },
  { w: 6, eq: "X_n = 1/(1 − p),   Đ = 1 + p   (Schulz–Flory)", ko: "축합 중합. 전환율 99%로도 100량체.", en: "Step-growth polymerization: 99% conversion gives only 100-mers." },
  { w: 6, eq: "Kc/ΔR = 1/M̄w + 2A₂c", ko: "정적 광산란(Zimm). 절편이 1/Mw, 기울기가 2A₂.", en: "Static light scattering (Zimm): intercept 1/Mw, slope 2A₂." },
  { w: 6, eq: "R_c = Nl,   R_rms = N^{1/2} l,   R_g = (N/6)^{1/2} l", ko: "자유 연결 사슬의 크기 척도. 크기는 결합 수의 제곱근에 비례.", en: "Size measures of a freely jointed chain; size scales as the square root of the number of bonds." },
  { w: 6, eq: "F = (k_BT/2l) ln[(1+ν)/(1−ν)] ≈ νk_BT/l,   ν = n/N", ko: "1차원 랜덤 코일의 엔트로피 복원력. 작은 신장에서 Hooke 법칙.", en: "Entropic restoring force of a 1D random coil; Hooke's law at small extension." },
  { w: 6, eq: "κ⁻¹ = 0.304/√c nm   (1:1 염, 물, 25 °C)", en_eq: "κ⁻¹ = 0.304/√c nm   (1:1 salt, water, 25 °C)", ko: "Debye 길이. 염이 늘면 이중층이 얇아져 DLVO 장벽이 낮아진다.", en: "Debye length. More salt thins the double layer and lowers the DLVO barrier." },
  { w: 6, eq: "v = (1/ν_J) d[J]/dt,   v = k[A]^a[B]^b", ko: "반응 속도의 정의와 속도식. 차수는 실험으로 정한다.", en: "Definition of the rate and the rate law; orders are found by experiment." },
  { w: 6, eq: "0차 [A] = [A]₀ − kt · 1차 ln([A]/[A]₀) = −kt · 2차 1/[A] = 1/[A]₀ + kt", en_eq: "0th [A] = [A]₀ − kt · 1st ln([A]/[A]₀) = −kt · 2nd 1/[A] = 1/[A]₀ + kt", ko: "적분 속도식. 어떤 그래프가 직선이 되는지로 차수를 판별한다.", en: "Integrated rate laws. The plot that comes out straight tells the order." },
  { w: 6, eq: "t½ = [A]₀/2k (0차),  ln2/k (1차),  1/(k[A]₀) (2차)", en_eq: "t½ = [A]₀/2k (0th),  ln2/k (1st),  1/(k[A]₀) (2nd)", ko: "반감기. 연속된 반감기가 줄면 0차, 일정하면 1차, 늘면 2차.", en: "Half-lives. Successive half-lives that shrink, stay constant or grow point to orders 0, 1, 2." },
  { w: 6, eq: "K = k/k′,   1/τ = k + k′   (A ⇌ B, 완화)", en_eq: "K = k/k′,   1/τ = k + k′   (A ⇌ B, relaxation)", ko: "평형 상수와 속도 상수의 관계, 완화 시간.", en: "Equilibrium constant from the rate constants, and the relaxation time." },
  { w: 6, eq: "k = A e^{−Ea/RT},   ln(k₂/k₁) = −(Ea/R)(1/T₂ − 1/T₁)", ko: "Arrhenius 식. 두 온도의 속도 상수만으로 Ea를 구한다.", en: "Arrhenius equation. Two rate constants at two temperatures give Ea." },
];

// ── concept quiz (answer index a) ───────────────────────────
export const QUIZ = [
  { w: 1, a: 0,
    ko: { q: "Rayleigh–Jeans 법칙이 짧은 파장에서 실패한 근본 이유는?", o: ["모든 모드가 진동수와 무관하게 평균 에너지 k_BT를 갖는다고 가정했다", "빛의 속도를 잘못 넣었다", "흑체 벽의 반사를 무시했다", "편광을 고려하지 않았다"], x: "등분배로 모든 모드에 k_BT를 주면 모드 수가 λ⁻⁴로 늘어나는 짧은 파장에서 에너지가 발산합니다. Planck는 에너지를 hν 단위로 양자화해 고주파 모드의 평균 에너지를 지수적으로 줄였습니다." },
    en: { q: "What is the root cause of the failure of the Rayleigh–Jeans law at short wavelengths?", o: ["It gives every mode an average energy k_BT regardless of frequency", "It used the wrong speed of light", "It ignored reflection at the cavity walls", "It ignored polarization"], x: "Equipartition gives every mode k_BT, and the number of modes grows as λ⁻⁴, so the energy diverges at short wavelengths. Planck quantized the energy in units of hν, which suppresses the average energy of high-frequency modes exponentially." } },
  { w: 1, a: 2,
    ko: { q: "흑체의 절대온도를 두 배로 올리면 단위면적당 총 방출능은?", o: ["2배", "4배", "16배", "변하지 않는다"], x: "Stefan–Boltzmann 법칙 E = σT⁴에 따라 2⁴ = 16배입니다. 피크 파장은 Wien 법칙에 따라 절반이 됩니다." },
    en: { q: "If the absolute temperature of a blackbody doubles, its total emissive power per unit area becomes", o: ["2 times larger", "4 times larger", "16 times larger", "unchanged"], x: "By the Stefan–Boltzmann law E = σT⁴, 2⁴ = 16 times. The peak wavelength halves by Wien's law." } },
  { w: 1, a: 1,
    ko: { q: "Lagrangian L이 좌표 q를 포함하지 않을 때(순환 좌표) 성립하는 것은?", o: ["q가 보존된다", "p = ∂L/∂q̇가 보존된다", "에너지가 보존되지 않는다", "운동 방정식이 없다"], x: "Euler–Lagrange 식 d/dt(∂L/∂q̇) = ∂L/∂q = 0이므로 일반화 운동량 p = ∂L/∂q̇가 시간에 대해 일정합니다. 대칭이 보존 법칙을 낳는 예입니다." },
    en: { q: "If the Lagrangian L does not contain the coordinate q (a cyclic coordinate), then", o: ["q is conserved", "p = ∂L/∂q̇ is conserved", "energy is not conserved", "there is no equation of motion"], x: "The Euler–Lagrange equation gives d/dt(∂L/∂q̇) = ∂L/∂q = 0, so the generalized momentum p = ∂L/∂q̇ is constant. A symmetry produces a conservation law." } },
  { w: 1, a: 3,
    ko: { q: "Schrödinger 방정식을 고유값 문제로 볼 때, 허용되는 에너지를 '고르는' 것은?", o: ["Planck 상수의 크기", "파동함수의 위상", "관측자의 측정", "경계조건(과 규격화 가능성)"], x: "미분 방정식 자체는 어떤 E에도 해를 갖지만, 경계에서 0이 되거나 무한대에서 사라지는 조건을 만족하는 E만 남습니다. 줄의 진동수가 양 끝 고정 조건으로 정해지는 것과 같은 원리입니다." },
    en: { q: "Viewing the Schrödinger equation as an eigenvalue problem, what selects the allowed energies?", o: ["The size of Planck's constant", "The phase of the wavefunction", "The observer's measurement", "The boundary conditions (and normalizability)"], x: "The differential equation has solutions for any E, but only certain E satisfy the conditions of vanishing at the walls or at infinity. It is the same reason a string fixed at both ends has discrete frequencies." } },
  { w: 2, a: 1,
    ko: { q: "1차원 상자의 길이를 두 배로 늘리면 Eₙ은?", o: ["2배", "1/4배", "1/2배", "변하지 않는다"], x: "Eₙ = n²h²/8mL² ∝ L⁻²이므로 1/4이 됩니다. 공액 사슬이 길수록 흡수 파장이 길어지는(붉어지는) 이유입니다." },
    en: { q: "If the length of a 1D box doubles, Eₙ becomes", o: ["2 times larger", "1/4", "1/2", "unchanged"], x: "Eₙ = n²h²/8mL² ∝ L⁻², so it falls to 1/4. This is why longer conjugated chains absorb at longer (redder) wavelengths." } },
  { w: 2, a: 2,
    ko: { q: "상자 속 입자의 n = 2 상태에서 입자를 상자 정중앙(x = L/2)에서 발견할 확률 밀도는?", o: ["최대", "1/L", "0", "2/L"], x: "ψ₂ = √(2/L) sin(2πx/L)은 x = L/2에 마디가 있어 그 점의 확률 밀도가 0입니다. 고전 입자라면 어디서나 같은 확률이었을 것입니다." },
    en: { q: "For n = 2 in a box, the probability density at the centre (x = L/2) is", o: ["maximal", "1/L", "zero", "2/L"], x: "ψ₂ = √(2/L) sin(2πx/L) has a node at x = L/2, so the density there is zero. A classical particle would be equally likely everywhere." } },
  { w: 2, a: 0,
    ko: { q: "넓은 직사각형 장벽의 투과 확률에 가장 민감하게 영향을 주는 것은?", o: ["장벽 폭 a와 √(V − E) (지수 e^{−2κa} 안)", "입자의 전하", "입사 파동의 진폭", "장벽 앞 영역의 길이"], x: "T ≈ 16(E/V)(1 − E/V)e^{−2κa}에서 폭과 κ = √(2m(V − E))/ℏ는 지수 안에 있습니다. STM이 원자 하나 높이 차이를 감지하는 근거입니다." },
    en: { q: "The transmission probability through a wide rectangular barrier is most sensitive to", o: ["the width a and √(V − E), inside e^{−2κa}", "the particle's charge", "the amplitude of the incident wave", "the length of the region before the barrier"], x: "In T ≈ 16(E/V)(1 − E/V)e^{−2κa}, the width and κ = √(2m(V − E))/ℏ sit in the exponent. That is why an STM can sense a single atomic step." } },
  { w: 2, a: 3,
    ko: { q: "[x̂, p̂] = iℏ가 뜻하는 것으로 가장 알맞은 것은?", o: ["x와 p는 항상 0이다", "x를 재면 p가 0이 된다", "x와 p는 같은 고유함수를 공유한다", "x와 p를 동시에 임의로 정확하게 정할 수 없다"], x: "교환하지 않는 연산자는 공통 고유함수를 갖지 않으며, ΔxΔp ≥ ℏ/2가 이 교환자에서 바로 나옵니다." },
    en: { q: "What does [x̂, p̂] = iℏ mean?", o: ["x and p are always zero", "measuring x sets p to zero", "x and p share eigenfunctions", "x and p cannot both be made arbitrarily sharp"], x: "Operators that do not commute have no common eigenfunctions, and ΔxΔp ≥ ℏ/2 follows directly from this commutator." } },
  { w: 3, a: 1,
    ko: { q: "조화진동자의 이웃한 두 준위 사이 간격은?", o: ["n에 비례해 커진다", "모든 n에서 ℏω로 같다", "n²에 비례한다", "n이 커질수록 0에 가까워진다"], x: "E_v = (v + ½)ℏω이므로 간격은 항상 ℏω입니다. 이원자 분자의 기본 진동선이 하나로 모이는 이유입니다(상자: n²에 비례, 수소: 1/n²)." },
    en: { q: "The spacing between neighbouring harmonic-oscillator levels", o: ["grows in proportion to n", "is ℏω for every n", "grows as n²", "goes to zero as n grows"], x: "E_v = (v + ½)ℏω, so the spacing is always ℏω, which is why a diatomic shows one fundamental line (compare the box, ∝ n², and hydrogen, ∝ 1/n²)." } },
  { w: 3, a: 2,
    ko: { q: "조화진동자의 바닥 상태 에너지가 0이 아닌 이유로 가장 알맞은 것은?", o: ["퍼텐셜에 상수가 더해져 있어서", "질량이 0이 아니어서", "x와 p가 동시에 0일 수 없기 때문(불확정성)", "열에너지 때문에"], x: "에너지가 0이려면 x = 0, p = 0이 동시에 정확해야 하는데 이는 ΔxΔp ≥ ℏ/2에 어긋납니다. 영점에너지 ℏω/2는 절대영도에서도 남습니다." },
    en: { q: "Why is the ground-state energy of the harmonic oscillator not zero?", o: ["A constant is added to the potential", "The mass is not zero", "x and p cannot both be zero (uncertainty)", "Thermal energy"], x: "Zero energy would need x = 0 and p = 0 exactly at the same time, violating ΔxΔp ≥ ℏ/2. The zero-point energy ℏω/2 remains even at absolute zero." } },
  { w: 3, a: 0,
    ko: { q: "l = 1 상태에 대해 옳은 것은?", o: ["|L| = √2 ℏ, m = −1, 0, +1", "|L| = ℏ, m = 0, 1", "|L| = 2ℏ, m = −1, +1", "|L| = √2 ℏ, m = 0만 가능"], x: "|L| = √(l(l+1))ℏ = √2 ℏ, m = −l … l = −1, 0, +1로 세 상태(p 궤도 셋)입니다." },
    en: { q: "For l = 1,", o: ["|L| = √2 ℏ, m = −1, 0, +1", "|L| = ℏ, m = 0, 1", "|L| = 2ℏ, m = −1, +1", "|L| = √2 ℏ, only m = 0"], x: "|L| = √(l(l+1))ℏ = √2 ℏ and m = −l … l = −1, 0, +1: three states, the three p orbitals." } },
  { w: 3, a: 3,
    ko: { q: "[L̂², L̂_z] = 0이고 [L̂_x, L̂_y] = iℏL̂_z일 때 동시에 정확히 정할 수 있는 조합은?", o: ["L_x와 L_y", "L_x, L_y, L_z 모두", "L_x와 L_z", "|L|과 L_z"], x: "L²과 L_z는 교환하므로 공통 고유상태 |l,m⟩을 갖습니다. 성분끼리는 교환하지 않아 하나만 정할 수 있고, 그래서 벡터 모델에서 L은 z축 주위의 원뿔 위에 그려집니다." },
    en: { q: "Given [L̂², L̂_z] = 0 and [L̂_x, L̂_y] = iℏL̂_z, which can be sharp simultaneously?", o: ["L_x and L_y", "all of L_x, L_y, L_z", "L_x and L_z", "|L| and L_z"], x: "L² and L_z commute and share the eigenstates |l,m⟩. The components do not commute, so only one can be fixed; that is why the vector model draws L on a cone about z." } },
  { w: 4, a: 1,
    ko: { q: "수소 원자 n = 3 준위의 축퇴도(스핀 제외)는?", o: ["3", "9", "6", "18"], x: "l = 0, 1, 2에 대해 2l + 1 = 1 + 3 + 5 = 9 = n²입니다. 스핀까지 세면 18." },
    en: { q: "The degeneracy of the hydrogen n = 3 level (without spin) is", o: ["3", "9", "6", "18"], x: "For l = 0, 1, 2: 1 + 3 + 5 = 9 = n². With spin, 18." } },
  { w: 4, a: 2,
    ko: { q: "Stern–Gerlach 실험에서 은 원자 빔이 두 갈래로 갈라진 것이 보여 주는 것은?", o: ["궤도 각운동량 l = 1", "원자의 전하", "전자의 고유 각운동량(스핀) s = ½", "자기장이 균일하다는 것"], x: "갈래 수는 2s + 1입니다. 두 갈래면 s = ½이며, l = 1이었다면 세 갈래가 나왔을 것입니다." },
    en: { q: "The splitting of a silver-atom beam into two in the Stern–Gerlach experiment shows", o: ["orbital angular momentum l = 1", "the charge of the atom", "an intrinsic angular momentum (spin) s = ½", "that the field is uniform"], x: "The number of beams is 2s + 1, so two beams mean s = ½; l = 1 would have given three." } },
  { w: 4, a: 0,
    ko: { q: "같은 온도에서 He(4 g/mol)의 평균 속력은 O₂(32 g/mol)의 몇 배인가?", o: ["√8 ≈ 2.8배", "8배", "1/8배", "같다"], x: "v̄ = √(8RT/πM) ∝ M^{−1/2}이므로 √(32/4) = √8 ≈ 2.83배입니다. 평균 운동에너지는 같습니다." },
    en: { q: "At the same temperature, the mean speed of He (4 g/mol) relative to O₂ (32 g/mol) is", o: ["√8 ≈ 2.8 times larger", "8 times larger", "1/8", "the same"], x: "v̄ = √(8RT/πM) ∝ M^{−1/2}, so √(32/4) = √8 ≈ 2.83. The mean kinetic energies are equal." } },
  { w: 4, a: 3,
    ko: { q: "온도를 고정하고 기체의 압력을 절반으로 줄이면 평균자유행로는?", o: ["절반", "변하지 않는다", "1/4", "두 배"], x: "λ = k_BT/(√2σp) ∝ 1/p이므로 두 배가 됩니다. 진공 장비에서 압력을 낮추는 이유입니다." },
    en: { q: "At fixed temperature, halving the pressure makes the mean free path", o: ["half as long", "unchanged", "a quarter as long", "twice as long"], x: "λ = k_BT/(√2σp) ∝ 1/p, so it doubles. That is why vacuum equipment lowers the pressure." } },
  { w: 5, a: 2,
    ko: { q: "London 분산 에너지의 거리 의존성은?", o: ["r⁻¹", "r⁻³", "r⁻⁶", "r⁻¹²"], x: "Keesom·유도·London 힘 모두 V ∝ −r⁻⁶입니다. r⁻¹²는 Lennard-Jones의 경험적 반발 항입니다." },
    en: { q: "The London dispersion energy depends on distance as", o: ["r⁻¹", "r⁻³", "r⁻⁶", "r⁻¹²"], x: "Keesom, induction and London all go as V ∝ −r⁻⁶. The r⁻¹² is the empirical repulsive term of the Lennard-Jones potential." } },
  { w: 5, a: 0,
    ko: { q: "Debye 식에서 극성 분자의 몰 분극이 온도가 오르면 줄어드는 이유는?", o: ["열운동이 쌍극자의 정렬을 흐트러뜨려 배향 항 μ²/3k_BT가 줄어서", "편극성 α가 온도에 반비례해서", "분자 수가 줄어서", "쌍극자 모멘트가 작아져서"], x: "전기장은 쌍극자를 정렬시키려 하고 열운동은 흐트러뜨립니다. 평균 정렬은 μE/3k_BT에 비례하므로 배향 기여가 1/T로 줄고, 전자 편극 α는 온도와 거의 무관합니다." },
    en: { q: "In the Debye equation, why does the molar polarization of a polar molecule decrease with temperature?", o: ["Thermal motion disorders dipole alignment, shrinking the orientation term μ²/3k_BT", "The polarizability α is inversely proportional to T", "The number of molecules drops", "The dipole moment shrinks"], x: "The field tries to align the dipoles and thermal motion scrambles them; the average alignment goes as μE/3k_BT, so the orientation term falls as 1/T. The electronic polarizability α hardly depends on T." } },
  { w: 5, a: 1,
    ko: { q: "물이 유리 모세관을 타고 올라가는 반면 수은은 내려가는 이유는?", o: ["수은이 더 무거워서", "접촉각이 물은 90°보다 작고 수은은 90°보다 커서", "수은의 표면장력이 0이어서", "유리가 물에 녹아서"], x: "h = 2σcosθ/(ρgr)에서 cosθ의 부호가 상승과 하강을 정합니다. 물은 유리를 적시고(θ < 90°), 수은은 적시지 않습니다(θ ≈ 140°)." },
    en: { q: "Why does water rise in a glass capillary while mercury is depressed?", o: ["Mercury is heavier", "Water's contact angle is below 90° and mercury's above 90°", "Mercury has zero surface tension", "Glass dissolves in water"], x: "In h = 2σcosθ/(ρgr), the sign of cosθ decides rise or fall. Water wets glass (θ < 90°); mercury does not (θ ≈ 140°)." } },
  { w: 5, a: 3,
    ko: { q: "Kelvin 식에 따르면 같은 액체의 작은 방울과 큰 방울이 함께 있으면 시간이 지나 어떻게 되는가?", o: ["둘 다 같은 속도로 증발한다", "작은 방울이 자란다", "아무 변화가 없다", "큰 방울이 작은 방울을 흡수하며 자란다"], x: "작은 방울은 곡률이 커서 증기압이 높으므로 증발하고, 그 증기가 증기압이 낮은 큰 방울에 응축합니다(Ostwald 숙성)." },
    en: { q: "By the Kelvin equation, what happens over time to small and large drops of the same liquid together?", o: ["Both evaporate at the same rate", "The small drops grow", "Nothing changes", "The large drops grow at the expense of the small ones"], x: "Small drops are more curved and have a higher vapour pressure, so they evaporate, and the vapour condenses on the large drops with lower vapour pressure (Ostwald ripening)." } },
  { w: 6, a: 0,
    ko: { q: "분자량 분포가 있는(다분산) 고분자 시료에서 항상 성립하는 것은?", o: ["M̄w > M̄n", "M̄w < M̄n", "M̄w = M̄n", "시료에 따라 다르다"], x: "M̄w는 질량으로 가중하므로 무거운 사슬에 더 큰 비중을 둡니다. 모든 사슬의 길이가 같을 때만 M̄w = M̄n, 곧 Đ = 1입니다." },
    en: { q: "For any polydisperse polymer sample,", o: ["M̄w > M̄n", "M̄w < M̄n", "M̄w = M̄n", "it depends on the sample"], x: "M̄w weights by mass, giving heavier chains more weight. Only when all chains are identical is M̄w = M̄n, that is Đ = 1." } },
  { w: 6, a: 2,
    ko: { q: "자유 연결 사슬에서 결합 수 N을 100배로 늘리면 R_rms는?", o: ["100배", "변하지 않는다", "10배", "10,000배"], x: "R_rms = N^{1/2} l이므로 √100 = 10배입니다. 펼친 길이 R_c = Nl은 100배가 되어 사슬은 상대적으로 더 촘촘히 뭉칩니다." },
    en: { q: "In a freely jointed chain, making N 100 times larger changes R_rms by a factor of", o: ["100", "1 (no change)", "10", "10,000"], x: "R_rms = N^{1/2} l, so √100 = 10. The contour length Nl grows 100 times, so the coil becomes relatively more compact." } },
  { w: 6, a: 1,
    ko: { q: "초기 농도를 두 배로 해도 반감기가 변하지 않는 반응은?", o: ["0차", "1차", "2차", "모든 차수"], x: "1차 반응의 t½ = ln2/k는 [A]₀와 무관합니다. 0차는 [A]₀에 비례, 2차는 [A]₀에 반비례합니다." },
    en: { q: "Which reaction has a half-life that does not change when the initial concentration doubles?", o: ["zeroth order", "first order", "second order", "every order"], x: "For first order, t½ = ln2/k is independent of [A]₀. For zeroth order t½ ∝ [A]₀, for second order t½ ∝ 1/[A]₀." } },
  { w: 6, a: 3,
    ko: { q: "촉매에 대해 옳은 것은?", o: ["정반응만 빠르게 한다", "평형 상수를 키운다", "반응 엔탈피를 낮춘다", "정반응과 역반응의 활성화 에너지를 같은 양만큼 낮추고 K는 그대로 둔다"], x: "촉매는 새로운 경로를 제공할 뿐 반응물과 생성물의 에너지는 바꾸지 않습니다. 그래서 두 방향이 같은 비율로 빨라지고 K = k/k′는 변하지 않습니다." },
    en: { q: "Which is true of a catalyst?", o: ["It speeds up only the forward reaction", "It increases the equilibrium constant", "It lowers the reaction enthalpy", "It lowers the forward and reverse activation energies by the same amount and leaves K unchanged"], x: "A catalyst provides a new pathway without changing the energies of reactants and products, so both directions speed up by the same factor and K = k/k′ stays the same." } },
];

// ── practice problems (new; hand-calculation) ───────────────
// each: w, id, ko/en: { t: title, q: statement, h: hint, s: [solution lines], a: answer }
export const PRACTICE = [
  { w: 1, id: "W1-A",
    ko: { t: "레이저 포인터와 흑체", q: "출력 5.0 mW, 파장 532 nm인 초록색 레이저 포인터가 있다. (a) 1초에 방출하는 광자 수를 구하라. (b) 방출 피크가 532 nm인 흑체의 온도를 구하라. (c) 그 온도, 그 파장에서 Rayleigh–Jeans 식은 Planck 식의 몇 배를 주는가?",
      h: "(c)는 x = hc/λk_BT로 두면 E_RJ/E_Planck = (eˣ − 1)/x. Wien 법칙의 λT를 넣으면 x가 숫자 하나로 정해진다.",
      s: ["(a) 광자 하나의 에너지 E = hc/λ = (6.626×10⁻³⁴)(2.998×10⁸)/(532×10⁻⁹) = 3.73×10⁻¹⁹ J",
          "N = P/E = (5.0×10⁻³ J s⁻¹)/(3.73×10⁻¹⁹ J) = 1.34×10¹⁶ s⁻¹",
          "(b) T = 2.898×10⁻³ m·K / 532×10⁻⁹ m = 5.45×10³ K (태양 표면과 비슷하다)",
          "(c) λT = 2.898×10⁻³ m·K이므로 x = hc/(λk_BT) = 1.4388×10⁻² / 2.898×10⁻³ = 4.965",
          "E_RJ/E_Planck = (e^{4.965} − 1)/4.965 = 28.7: 피크에서 고전 이론은 이미 약 29배 과대평가한다"],
      a: "(a) 1.34×10¹⁶ s⁻¹ (b) 5.45×10³ K (c) 약 29배" },
    en: { t: "A laser pointer and a blackbody", q: "A green laser pointer emits 5.0 mW at 532 nm. (a) How many photons does it emit per second? (b) At what temperature does a blackbody peak at 532 nm? (c) At that temperature and wavelength, by what factor does the Rayleigh–Jeans law exceed Planck's law?",
      h: "For (c), with x = hc/λk_BT the ratio is E_RJ/E_Planck = (eˣ − 1)/x. Inserting Wien's λT fixes x as a single number.",
      s: ["(a) Energy per photon E = hc/λ = (6.626×10⁻³⁴)(2.998×10⁸)/(532×10⁻⁹) = 3.73×10⁻¹⁹ J",
          "N = P/E = (5.0×10⁻³ J s⁻¹)/(3.73×10⁻¹⁹ J) = 1.34×10¹⁶ s⁻¹",
          "(b) T = 2.898×10⁻³ m·K / 532×10⁻⁹ m = 5.45×10³ K (close to the solar surface)",
          "(c) λT = 2.898×10⁻³ m·K, so x = hc/(λk_BT) = 1.4388×10⁻² / 2.898×10⁻³ = 4.965",
          "E_RJ/E_Planck = (e^{4.965} − 1)/4.965 = 28.7: at the peak the classical theory already overestimates by about 29 times"],
      a: "(a) 1.34×10¹⁶ s⁻¹ (b) 5.45×10³ K (c) about 29 times" } },
  { w: 1, id: "W1-B",
    ko: { t: "단진자의 Lagrangian", q: "질량 m, 길이 l인 단진자의 각도를 θ라 하자. (a) L = T − U를 쓰고 Euler–Lagrange 방정식으로 운동 방정식을 구하라. (b) 작은 진폭에서 l = 0.50 m인 진자의 주기를 구하라(g = 9.81 m s⁻²). (c) 일반화 운동량 p_θ와 Hamiltonian H(θ, p_θ)를 구하라.",
      h: "T = ½ml²θ̇², 퍼텐셜은 매단 점 기준 U = −mgl cos θ. 작은 θ에서 sin θ ≈ θ.",
      s: ["(a) L = ½ml²θ̇² + mgl cos θ",
          "∂L/∂θ̇ = ml²θ̇,  ∂L/∂θ = −mgl sin θ  →  ml²θ̈ = −mgl sin θ  →  θ̈ = −(g/l) sin θ",
          "(b) sin θ ≈ θ이면 θ̈ = −(g/l)θ, ω = √(g/l), 주기 T = 2π√(l/g) = 2π√(0.50/9.81) = 1.42 s",
          "(c) p_θ = ∂L/∂θ̇ = ml²θ̇ (각운동량)",
          "H = p_θθ̇ − L = p_θ²/2ml² − mgl cos θ = T + U"],
      a: "(a) θ̈ = −(g/l) sin θ (b) 1.42 s (c) p_θ = ml²θ̇, H = p_θ²/2ml² − mgl cos θ" },
    en: { t: "Lagrangian of a simple pendulum", q: "A simple pendulum has mass m, length l and angle θ. (a) Write L = T − U and get the equation of motion from the Euler–Lagrange equation. (b) Find the small-amplitude period for l = 0.50 m (g = 9.81 m s⁻²). (c) Find the generalized momentum p_θ and the Hamiltonian H(θ, p_θ).",
      h: "T = ½ml²θ̇², and measured from the pivot U = −mgl cos θ. For small θ, sin θ ≈ θ.",
      s: ["(a) L = ½ml²θ̇² + mgl cos θ",
          "∂L/∂θ̇ = ml²θ̇,  ∂L/∂θ = −mgl sin θ  →  ml²θ̈ = −mgl sin θ  →  θ̈ = −(g/l) sin θ",
          "(b) With sin θ ≈ θ, θ̈ = −(g/l)θ, ω = √(g/l), period T = 2π√(l/g) = 2π√(0.50/9.81) = 1.42 s",
          "(c) p_θ = ∂L/∂θ̇ = ml²θ̇ (the angular momentum)",
          "H = p_θθ̇ − L = p_θ²/2ml² − mgl cos θ = T + U"],
      a: "(a) θ̈ = −(g/l) sin θ (b) 1.42 s (c) p_θ = ml²θ̇, H = p_θ²/2ml² − mgl cos θ" } },
  { w: 2, id: "W2-A",
    ko: { t: "전자 회절과 불확정성", q: "정지한 전자를 150 V로 가속했다. (a) 운동량과 de Broglie 파장을 구하라. (b) 이 전자의 위치를 Δx = 0.10 nm 안으로 알고 있다면 운동량 불확정성의 최솟값은 얼마이고, (a)의 운동량에 비해 몇 %인가?",
      h: "eV = p²/2m. 최소 불확정성은 Δp = ℏ/2Δx.",
      s: ["(a) p = √(2m_e eV) = √(2 × 9.109×10⁻³¹ × 1.602×10⁻¹⁹ × 150) = 6.62×10⁻²⁴ kg m s⁻¹",
          "λ = h/p = 6.626×10⁻³⁴ / 6.62×10⁻²⁴ = 1.00×10⁻¹⁰ m = 0.100 nm (원자 간격 정도라 결정에서 회절한다)",
          "(b) Δp_min = ℏ/2Δx = 1.0546×10⁻³⁴ / (2 × 0.10×10⁻⁹) = 5.27×10⁻²⁵ kg m s⁻¹",
          "Δp/p = 5.27×10⁻²⁵ / 6.62×10⁻²⁴ = 0.080, 곧 약 8%"],
      a: "(a) 6.62×10⁻²⁴ kg m s⁻¹, 0.100 nm (b) 5.27×10⁻²⁵ kg m s⁻¹, 약 8%" },
    en: { t: "Electron diffraction and uncertainty", q: "An electron at rest is accelerated through 150 V. (a) Find its momentum and de Broglie wavelength. (b) If its position is known to within Δx = 0.10 nm, what is the minimum momentum uncertainty, and what percentage of the momentum in (a) is it?",
      h: "eV = p²/2m. The minimum uncertainty is Δp = ℏ/2Δx.",
      s: ["(a) p = √(2m_e eV) = √(2 × 9.109×10⁻³¹ × 1.602×10⁻¹⁹ × 150) = 6.62×10⁻²⁴ kg m s⁻¹",
          "λ = h/p = 6.626×10⁻³⁴ / 6.62×10⁻²⁴ = 1.00×10⁻¹⁰ m = 0.100 nm (about an atomic spacing, so crystals diffract it)",
          "(b) Δp_min = ℏ/2Δx = 1.0546×10⁻³⁴ / (2 × 0.10×10⁻⁹) = 5.27×10⁻²⁵ kg m s⁻¹",
          "Δp/p = 5.27×10⁻²⁵ / 6.62×10⁻²⁴ = 0.080, about 8%"],
      a: "(a) 6.62×10⁻²⁴ kg m s⁻¹, 0.100 nm (b) 5.27×10⁻²⁵ kg m s⁻¹, about 8%" } },
  { w: 2, id: "W2-B",
    ko: { t: "공액 분자의 자유 전자 모형", q: "π 전자 8개가 길이 L = 0.95 nm인 1차원 상자 안에 있다고 보자(한 준위에 전자 2개). (a) HOMO와 LUMO의 양자수를 정하고, HOMO → LUMO 전이의 에너지(eV)와 흡수 파장을 구하라. (b) 바닥 상태(n = 1) 전자를 상자 왼쪽 1/3 구간(0 ≤ x ≤ L/3)에서 발견할 확률을 구하라. 고전 입자라면 얼마였겠는가?",
      h: "ΔE = (n_LUMO² − n_HOMO²)h²/8mL². (b)는 ∫sin²(kx)dx = x/2 − sin(2kx)/4k.",
      s: ["(a) 전자 8개는 n = 1–4를 채우므로 HOMO n = 4, LUMO n = 5",
          "E₁ = h²/8m_eL² = (6.626×10⁻³⁴)² / (8 × 9.109×10⁻³¹ × (0.95×10⁻⁹)²) = 6.68×10⁻²⁰ J",
          "ΔE = (25 − 16)E₁ = 9E₁ = 6.01×10⁻¹⁹ J = 3.75 eV,  λ = 1239.84/3.75 = 331 nm (자외선)",
          "(b) P = (2/L)∫₀^{L/3} sin²(πx/L)dx = (2/L)[x/2 − (L/4π) sin(2πx/L)]₀^{L/3} = 1/3 − sin(2π/3)/2π",
          "P = 0.3333 − 0.8660/6.2832 = 0.196. 고전 입자는 어디서나 같으므로 1/3 = 0.333: 양자 입자는 가운데에 몰려 있다"],
      a: "(a) n = 4 → 5, 3.75 eV, 331 nm (b) 0.196 (고전: 0.333)" },
    en: { t: "Free-electron model of a conjugated molecule", q: "Treat 8 π electrons as particles in a 1D box of length L = 0.95 nm (two electrons per level). (a) Identify the HOMO and LUMO quantum numbers and find the HOMO → LUMO transition energy (eV) and absorption wavelength. (b) Find the probability that a ground-state (n = 1) electron is in the left third of the box (0 ≤ x ≤ L/3). What would it be for a classical particle?",
      h: "ΔE = (n_LUMO² − n_HOMO²)h²/8mL². For (b), ∫sin²(kx)dx = x/2 − sin(2kx)/4k.",
      s: ["(a) 8 electrons fill n = 1–4, so the HOMO is n = 4 and the LUMO n = 5",
          "E₁ = h²/8m_eL² = (6.626×10⁻³⁴)² / (8 × 9.109×10⁻³¹ × (0.95×10⁻⁹)²) = 6.68×10⁻²⁰ J",
          "ΔE = (25 − 16)E₁ = 9E₁ = 6.01×10⁻¹⁹ J = 3.75 eV,  λ = 1239.84/3.75 = 331 nm (ultraviolet)",
          "(b) P = (2/L)∫₀^{L/3} sin²(πx/L)dx = (2/L)[x/2 − (L/4π) sin(2πx/L)]₀^{L/3} = 1/3 − sin(2π/3)/2π",
          "P = 0.3333 − 0.8660/6.2832 = 0.196. A classical particle is uniform, giving 1/3 = 0.333: the quantum particle crowds towards the middle"],
      a: "(a) n = 4 → 5, 3.75 eV, 331 nm (b) 0.196 (classical: 0.333)" } },
  { w: 2, id: "W2-C",
    ko: { t: "터널링: 폭이 두 배면?", q: "에너지 1.0 eV인 전자가 높이 2.0 eV, 폭 0.50 nm인 직사각형 장벽에 입사한다. (a) κ와 투과 확률 T를 근사식으로 구하라. (b) 폭이 1.0 nm이면 T는 몇 배로 줄어드는가?",
      h: "κ = √(2m(V − E))/ℏ, T ≈ 16(E/V)(1 − E/V)e^{−2κa}. 폭이 두 배면 지수가 두 배.",
      s: ["(a) κ = √(2 × 9.109×10⁻³¹ × 1.0 × 1.602×10⁻¹⁹)/1.0546×10⁻³⁴ = 5.12×10⁹ m⁻¹",
          "2κa = 2 × 5.12×10⁹ × 0.50×10⁻⁹ = 5.12",
          "T ≈ 16 × 0.5 × 0.5 × e^{−5.12} = 4 × 5.96×10⁻³ = 2.4×10⁻² (정확한 식은 2.36×10⁻²)",
          "(b) a = 1.0 nm: 2κa = 10.25, T ≈ 4e^{−10.25} = 1.4×10⁻⁴",
          "비율 2.4×10⁻² / 1.4×10⁻⁴ ≈ 170배 감소: 폭 0.5 nm 차이가 두 자릿수 이상의 차이를 만든다(STM의 원리)"],
      a: "(a) κ = 5.12×10⁹ m⁻¹, T ≈ 2.4×10⁻² (b) 1.4×10⁻⁴, 약 170배 감소" },
    en: { t: "Tunnelling: what if the barrier is twice as wide?", q: "An electron with energy 1.0 eV meets a rectangular barrier of height 2.0 eV and width 0.50 nm. (a) Find κ and, with the approximate formula, the transmission probability T. (b) By what factor does T drop if the width is 1.0 nm?",
      h: "κ = √(2m(V − E))/ℏ and T ≈ 16(E/V)(1 − E/V)e^{−2κa}. Doubling the width doubles the exponent.",
      s: ["(a) κ = √(2 × 9.109×10⁻³¹ × 1.0 × 1.602×10⁻¹⁹)/1.0546×10⁻³⁴ = 5.12×10⁹ m⁻¹",
          "2κa = 2 × 5.12×10⁹ × 0.50×10⁻⁹ = 5.12",
          "T ≈ 16 × 0.5 × 0.5 × e^{−5.12} = 4 × 5.96×10⁻³ = 2.4×10⁻² (exact formula: 2.36×10⁻²)",
          "(b) a = 1.0 nm: 2κa = 10.25, T ≈ 4e^{−10.25} = 1.4×10⁻⁴",
          "Ratio 2.4×10⁻² / 1.4×10⁻⁴ ≈ 170: an extra 0.5 nm costs more than two orders of magnitude (the principle of the STM)"],
      a: "(a) κ = 5.12×10⁹ m⁻¹, T ≈ 2.4×10⁻² (b) 1.4×10⁻⁴, about 170 times smaller" } },
  { w: 3, id: "W3-A",
    ko: { t: "이원자 분자의 진동", q: "힘상수 k = 500 N m⁻¹, 환산질량 μ = 1.60×10⁻²⁷ kg인 이원자 분자를 조화진동자로 보자. (a) 진동 각진동수와 파수(cm⁻¹)를 구하라. (b) 영점에너지를 J, eV, kJ mol⁻¹로 구하라. (c) 사다리 연산자로 바닥 상태의 ⟨x²⟩를 구하고 x_rms를 pm로 구하라.",
      h: "x̂ = √(ℏ/2μω)(â + â†). ⟨0|(â + â†)²|0⟩에서 살아남는 항은 ââ†뿐.",
      s: ["(a) ω = √(k/μ) = √(500/1.60×10⁻²⁷) = 5.59×10¹⁴ rad s⁻¹",
          "ν̃ = ω/2πc = 5.59×10¹⁴ / (2π × 2.998×10¹⁰ cm s⁻¹) = 2.97×10³ cm⁻¹",
          "(b) E₀ = ½ℏω = ½ × 1.0546×10⁻³⁴ × 5.59×10¹⁴ = 2.95×10⁻²⁰ J = 0.184 eV = 17.8 kJ mol⁻¹",
          "(c) (â + â†)² = â² + ââ† + â†â + â†², 바닥 상태에서 ⟨0|ââ†|0⟩ = 1만 남는다",
          "⟨x²⟩₀ = ℏ/2μω = 1.0546×10⁻³⁴ / (2 × 1.60×10⁻²⁷ × 5.59×10¹⁴) = 5.90×10⁻²³ m²,  x_rms = 7.68 pm"],
      a: "(a) 5.59×10¹⁴ rad s⁻¹, 2.97×10³ cm⁻¹ (b) 2.95×10⁻²⁰ J = 0.184 eV = 17.8 kJ mol⁻¹ (c) 5.90×10⁻²³ m², 7.68 pm" },
    en: { t: "Vibration of a diatomic molecule", q: "Treat a diatomic molecule with force constant k = 500 N m⁻¹ and reduced mass μ = 1.60×10⁻²⁷ kg as a harmonic oscillator. (a) Find the angular frequency and the wavenumber (cm⁻¹). (b) Find the zero-point energy in J, eV and kJ mol⁻¹. (c) Use ladder operators to find ⟨x²⟩ in the ground state, and x_rms in pm.",
      h: "x̂ = √(ℏ/2μω)(â + â†). In ⟨0|(â + â†)²|0⟩ only the ââ† term survives.",
      s: ["(a) ω = √(k/μ) = √(500/1.60×10⁻²⁷) = 5.59×10¹⁴ rad s⁻¹",
          "ν̃ = ω/2πc = 5.59×10¹⁴ / (2π × 2.998×10¹⁰ cm s⁻¹) = 2.97×10³ cm⁻¹",
          "(b) E₀ = ½ℏω = ½ × 1.0546×10⁻³⁴ × 5.59×10¹⁴ = 2.95×10⁻²⁰ J = 0.184 eV = 17.8 kJ mol⁻¹",
          "(c) (â + â†)² = â² + ââ† + â†â + â†²; in the ground state only ⟨0|ââ†|0⟩ = 1 survives",
          "⟨x²⟩₀ = ℏ/2μω = 1.0546×10⁻³⁴ / (2 × 1.60×10⁻²⁷ × 5.59×10¹⁴) = 5.90×10⁻²³ m²,  x_rms = 7.68 pm"],
      a: "(a) 5.59×10¹⁴ rad s⁻¹, 2.97×10³ cm⁻¹ (b) 2.95×10⁻²⁰ J = 0.184 eV = 17.8 kJ mol⁻¹ (c) 5.90×10⁻²³ m², 7.68 pm" } },
  { w: 3, id: "W3-B",
    ko: { t: "l = 2 각운동량", q: "l = 2인 상태에 대해 (a) |L|과 가능한 L_z 값을 구하라. (b) 벡터 모델에서 L과 z축 사이의 최소 각을 구하라. (c) L̂₊|2,1⟩과 L̂₊|2,2⟩를 계산하라.",
      h: "L̂₊|l,m⟩ = ℏ√((l − m)(l + m + 1))|l, m+1⟩.",
      s: ["(a) |L| = √(2·3) ℏ = √6 ℏ = 2.58×10⁻³⁴ J s,  L_z = mℏ, m = −2, −1, 0, 1, 2 (다섯 개 = d 궤도 다섯)",
          "(b) 최소 각은 m = 2: cos θ = 2/√6 = 0.816, θ = 35.3°. L은 z축과 완전히 나란할 수 없다",
          "(c) L̂₊|2,1⟩ = ℏ√((2 − 1)(2 + 1 + 1))|2,2⟩ = ℏ√4 |2,2⟩ = 2ℏ|2,2⟩",
          "L̂₊|2,2⟩ = ℏ√(0·5)|2,3⟩ = 0: 사다리의 맨 위에서 멈춘다"],
      a: "(a) √6 ℏ, m = −2…2 (b) 35.3° (c) 2ℏ|2,2⟩, 0" },
    en: { t: "Angular momentum with l = 2", q: "For a state with l = 2, (a) find |L| and the possible values of L_z. (b) Find the smallest angle between L and the z axis in the vector model. (c) Evaluate L̂₊|2,1⟩ and L̂₊|2,2⟩.",
      h: "L̂₊|l,m⟩ = ℏ√((l − m)(l + m + 1))|l, m+1⟩.",
      s: ["(a) |L| = √(2·3) ℏ = √6 ℏ = 2.58×10⁻³⁴ J s;  L_z = mℏ with m = −2, −1, 0, 1, 2 (five, the five d orbitals)",
          "(b) The smallest angle is for m = 2: cos θ = 2/√6 = 0.816, θ = 35.3°. L can never lie along z",
          "(c) L̂₊|2,1⟩ = ℏ√((2 − 1)(2 + 1 + 1))|2,2⟩ = ℏ√4 |2,2⟩ = 2ℏ|2,2⟩",
          "L̂₊|2,2⟩ = ℏ√(0·5)|2,3⟩ = 0: the ladder stops at the top"],
      a: "(a) √6 ℏ, m = −2…2 (b) 35.3° (c) 2ℏ|2,2⟩, 0" } },
  { w: 4, id: "W4-A",
    ko: { t: "수소의 Paschen α선", q: "수소 원자의 n = 4 → 3 전이에 대해 (a) 방출 광자의 에너지와 파장을 구하라(Eₙ = −13.6057 eV/n²). (b) n = 4 준위의 축퇴도를 스핀 없이, 스핀 포함으로 구하라. (c) n = 3에서 전자를 떼어 내는 데 필요한 에너지는?",
      h: "λ = 1239.84 eV·nm / ΔE. 축퇴도 = Σ(2l + 1).",
      s: ["(a) ΔE = 13.6057 (1/9 − 1/16) = 13.6057 × 7/144 = 0.661 eV",
          "λ = 1239.84/0.6614 = 1875 nm (근적외선, Paschen 계열 첫 선)",
          "(b) l = 0, 1, 2, 3: 1 + 3 + 5 + 7 = 16 = n², 스핀 포함 32",
          "(c) E_ion = 13.6057/9 = 1.51 eV"],
      a: "(a) 0.661 eV, 1875 nm (b) 16, 32 (c) 1.51 eV" },
    en: { t: "Hydrogen's Paschen-α line", q: "For the hydrogen n = 4 → 3 transition, (a) find the photon energy and wavelength (Eₙ = −13.6057 eV/n²). (b) Find the degeneracy of n = 4 without and with spin. (c) How much energy removes the electron from n = 3?",
      h: "λ = 1239.84 eV·nm / ΔE. Degeneracy = Σ(2l + 1).",
      s: ["(a) ΔE = 13.6057 (1/9 − 1/16) = 13.6057 × 7/144 = 0.661 eV",
          "λ = 1239.84/0.6614 = 1875 nm (near infrared, the first Paschen line)",
          "(b) l = 0, 1, 2, 3: 1 + 3 + 5 + 7 = 16 = n², 32 with spin",
          "(c) E_ion = 13.6057/9 = 1.51 eV"],
      a: "(a) 0.661 eV, 1875 nm (b) 16, 32 (c) 1.51 eV" } },
  { w: 4, id: "W4-B",
    ko: { t: "산소 분자의 운동론", q: "300 K의 O₂(M = 32.0 g mol⁻¹)에 대해 (a) 최빈 속력, 평균 속력, rms 속력을 구하라. (b) 충돌 단면적 σ = 0.40 nm²로 보고 1 bar에서의 평균자유행로를 구하라. (c) 평균자유행로가 1.0 mm가 되려면 압력을 얼마로 낮춰야 하는가? (d) 같은 조건에서 H₂(2.0 g mol⁻¹)는 O₂보다 몇 배 빨리 분출되는가?",
      h: "M은 kg mol⁻¹로. λ = k_BT/(√2σp) ∝ 1/p.",
      s: ["(a) v_mp = √(2RT/M) = √(2 × 8.314 × 300/0.0320) = 395 m s⁻¹",
          "v̄ = √(8RT/πM) = 446 m s⁻¹,  v_rms = √(3RT/M) = 484 m s⁻¹ (비 1 : 1.128 : 1.225)",
          "(b) λ = k_BT/(√2σp) = (1.381×10⁻²³ × 300)/(1.414 × 0.40×10⁻¹⁸ × 1.0×10⁵) = 7.3×10⁻⁸ m = 73 nm",
          "(c) p = k_BT/(√2σλ) = 4.14×10⁻²¹/(1.414 × 0.40×10⁻¹⁸ × 1.0×10⁻³) = 7.3 Pa",
          "(d) 분출 속도 ∝ 1/√M: √(32.0/2.0) = 4.0배"],
      a: "(a) 395, 446, 484 m s⁻¹ (b) 73 nm (c) 7.3 Pa (d) 4.0배" },
    en: { t: "Kinetic theory of oxygen", q: "For O₂ (M = 32.0 g mol⁻¹) at 300 K, (a) find the most probable, mean and rms speeds. (b) Taking the collision cross-section σ = 0.40 nm², find the mean free path at 1 bar. (c) To what pressure must the gas be pumped for a 1.0 mm mean free path? (d) Under the same conditions, how many times faster does H₂ (2.0 g mol⁻¹) effuse than O₂?",
      h: "Use M in kg mol⁻¹. λ = k_BT/(√2σp) ∝ 1/p.",
      s: ["(a) v_mp = √(2RT/M) = √(2 × 8.314 × 300/0.0320) = 395 m s⁻¹",
          "v̄ = √(8RT/πM) = 446 m s⁻¹,  v_rms = √(3RT/M) = 484 m s⁻¹ (ratio 1 : 1.128 : 1.225)",
          "(b) λ = k_BT/(√2σp) = (1.381×10⁻²³ × 300)/(1.414 × 0.40×10⁻¹⁸ × 1.0×10⁵) = 7.3×10⁻⁸ m = 73 nm",
          "(c) p = k_BT/(√2σλ) = 4.14×10⁻²¹/(1.414 × 0.40×10⁻¹⁸ × 1.0×10⁻³) = 7.3 Pa",
          "(d) Effusion rate ∝ 1/√M: √(32.0/2.0) = 4.0 times"],
      a: "(a) 395, 446, 484 m s⁻¹ (b) 73 nm (c) 7.3 Pa (d) 4.0 times" } },
  { w: 5, id: "W5-A",
    ko: { t: "Debye 그림 두 점으로 μ와 α 구하기", q: "어떤 극성 기체의 몰 분극을 두 온도에서 쟀다(설명용 가상 데이터): 300 K에서 57.6 cm³ mol⁻¹, 400 K에서 50.3 cm³ mol⁻¹. Debye 식 P_m = (4π/3)N_Aα′ + N_Aμ²/(9ε₀k_BT)를 이용해 (a) 기울기와 절편, (b) 쌍극자 모멘트(D), (c) 편극성 부피 α′(Å³)를 구하라.",
      h: "P_m = A + B/T로 놓고 두 점에서 B와 A를 구한다. 단위를 m³ mol⁻¹로 바꿔서 계산한다.",
      s: ["(a) B = (57.6 − 50.3)/(1/300 − 1/400) = 7.3/8.333×10⁻⁴ = 8.76×10³ cm³ K mol⁻¹",
          "A = 57.6 − 8760/300 = 28.4 cm³ mol⁻¹",
          "(b) μ² = 9ε₀k_BB/N_A = 9 × 8.854×10⁻¹² × 1.381×10⁻²³ × 8.76×10⁻³ / 6.022×10²³ = 1.60×10⁻⁵⁹ C² m²",
          "μ = 4.00×10⁻³⁰ C m = 1.20 D",
          "(c) α′ = 3A/(4πN_A) = 3 × 28.4×10⁻⁶ / (4π × 6.022×10²³) = 1.13×10⁻²⁹ m³ = 11.3 Å³"],
      a: "(a) B = 8.76×10³ cm³ K mol⁻¹, A = 28.4 cm³ mol⁻¹ (b) 1.20 D (c) 11.3 Å³" },
    en: { t: "μ and α from two points on a Debye plot", q: "The molar polarization of a polar gas was measured at two temperatures (illustrative data): 57.6 cm³ mol⁻¹ at 300 K and 50.3 cm³ mol⁻¹ at 400 K. Using the Debye equation P_m = (4π/3)N_Aα′ + N_Aμ²/(9ε₀k_BT), find (a) the slope and intercept, (b) the dipole moment (D), and (c) the polarizability volume α′ (Å³).",
      h: "Write P_m = A + B/T and get B and A from the two points. Convert to m³ mol⁻¹ for the SI calculation.",
      s: ["(a) B = (57.6 − 50.3)/(1/300 − 1/400) = 7.3/8.333×10⁻⁴ = 8.76×10³ cm³ K mol⁻¹",
          "A = 57.6 − 8760/300 = 28.4 cm³ mol⁻¹",
          "(b) μ² = 9ε₀k_BB/N_A = 9 × 8.854×10⁻¹² × 1.381×10⁻²³ × 8.76×10⁻³ / 6.022×10²³ = 1.60×10⁻⁵⁹ C² m²",
          "μ = 4.00×10⁻³⁰ C m = 1.20 D",
          "(c) α′ = 3A/(4πN_A) = 3 × 28.4×10⁻⁶ / (4π × 6.022×10²³) = 1.13×10⁻²⁹ m³ = 11.3 Å³"],
      a: "(a) B = 8.76×10³ cm³ K mol⁻¹, A = 28.4 cm³ mol⁻¹ (b) 1.20 D (c) 11.3 Å³" } },
  { w: 5, id: "W5-B",
    ko: { t: "모세관으로 표면장력 재기, Kelvin 식", q: "(a) 반지름 0.20 mm인 깨끗한 유리 모세관에서 밀도 789 kg m⁻³인 액체가 2.95 cm 올라갔다(θ ≈ 0). 표면장력을 구하라. (b) 물(σ = 72.0 mN m⁻¹) 속 반지름 1.0 μm 기포의 안팎 압력 차를 구하라. (c) 298 K에서 반지름 2 nm와 20 nm인 물방울의 증기압 비 p(2 nm)/p(20 nm)를 구하라(V_m = 1.807×10⁻⁵ m³ mol⁻¹).",
      h: "(a) h = 2σcosθ/ρgr을 σ에 대해 푼다. (c) 두 Kelvin 식을 나누면 ln(p₁/p₂) = (2σV_m/RT)(1/r₁ − 1/r₂).",
      s: ["(a) σ = ρghr/2 = 789 × 9.81 × 0.0295 × 0.20×10⁻³ / 2 = 2.28×10⁻² N m⁻¹ = 22.8 mN m⁻¹ (에탄올과 비슷)",
          "(b) Δp = 2σ/r = 2 × 0.0720 / 1.0×10⁻⁶ = 1.44×10⁵ Pa (약 1.4 bar)",
          "(c) 2σV_m/RT = 2 × 0.0720 × 1.807×10⁻⁵ / (8.314 × 298) = 1.05×10⁻⁹ m = 1.05 nm",
          "ln(p₁/p₂) = 1.05 nm × (1/2 − 1/20) nm⁻¹ = 0.473,  p₁/p₂ = 1.60: 작은 방울이 증발하고 큰 방울이 자란다"],
      a: "(a) 22.8 mN m⁻¹ (b) 1.44×10⁵ Pa (c) 1.60" },
    en: { t: "Measuring surface tension with a capillary; the Kelvin equation", q: "(a) A liquid of density 789 kg m⁻³ rises 2.95 cm in a clean glass capillary of radius 0.20 mm (θ ≈ 0). Find its surface tension. (b) Find the pressure difference across a bubble of radius 1.0 μm in water (σ = 72.0 mN m⁻¹). (c) At 298 K, find the vapour-pressure ratio p(2 nm)/p(20 nm) for water drops of radius 2 nm and 20 nm (V_m = 1.807×10⁻⁵ m³ mol⁻¹).",
      h: "(a) Solve h = 2σcosθ/ρgr for σ. (c) Dividing two Kelvin equations gives ln(p₁/p₂) = (2σV_m/RT)(1/r₁ − 1/r₂).",
      s: ["(a) σ = ρghr/2 = 789 × 9.81 × 0.0295 × 0.20×10⁻³ / 2 = 2.28×10⁻² N m⁻¹ = 22.8 mN m⁻¹ (close to ethanol)",
          "(b) Δp = 2σ/r = 2 × 0.0720 / 1.0×10⁻⁶ = 1.44×10⁵ Pa (about 1.4 bar)",
          "(c) 2σV_m/RT = 2 × 0.0720 × 1.807×10⁻⁵ / (8.314 × 298) = 1.05×10⁻⁹ m = 1.05 nm",
          "ln(p₁/p₂) = 1.05 nm × (1/2 − 1/20) nm⁻¹ = 0.473,  p₁/p₂ = 1.60: the small drops evaporate and the large ones grow"],
      a: "(a) 22.8 mN m⁻¹ (b) 1.44×10⁵ Pa (c) 1.60" } },
  { w: 6, id: "W6-A",
    ko: { t: "분자량 분포, 축합 중합, Debye 길이", q: "(a) 분자량 10, 30, 90 kg mol⁻¹인 단분산 사슬이 개수비 2 : 3 : 1로 섞여 있다. M̄n, M̄w, Đ를 구하라. (b) 축합 중합에서 수평균 중합도 200을 얻으려면 전환율이 얼마여야 하고, 그때 Đ는? (c) 1:1 염 5.0 mM과 0.50 M에서 Debye 길이를 구하고, 콜로이드 안정성에 어떤 차이가 있을지 말하라.",
      h: "(a) 개수비가 곧 Nᵢ. (b) X_n = 1/(1 − p), Đ = 1 + p. (c) κ⁻¹ = 0.304/√c nm.",
      s: ["(a) M̄n = (2×10 + 3×30 + 1×90)/6 = 200/6 = 33.3 kg mol⁻¹",
          "M̄w = (2×10² + 3×30² + 1×90²)/(2×10 + 3×30 + 1×90) = 11000/200 = 55.0 kg mol⁻¹,  Đ = 1.65",
          "(b) 1/(1 − p) = 200 → p = 0.995 (99.5%),  Đ = 1 + p = 1.995",
          "(c) 5.0 mM: κ⁻¹ = 0.304/√0.0050 = 4.3 nm,  0.50 M: κ⁻¹ = 0.43 nm",
          "염이 많으면 이중층이 얇아져 정전 반발이 짧은 거리에서만 작용하므로 DLVO 장벽이 낮아지고 응집되기 쉽다"],
      a: "(a) 33.3, 55.0 kg mol⁻¹, Đ = 1.65 (b) p = 0.995, Đ = 1.995 (c) 4.3 nm, 0.43 nm" },
    en: { t: "Molar-mass distribution, step growth, Debye length", q: "(a) Monodisperse chains of 10, 30 and 90 kg mol⁻¹ are mixed in the number ratio 2 : 3 : 1. Find M̄n, M̄w and Đ. (b) What conversion gives a number-average degree of polymerization of 200 in step growth, and what is Đ then? (c) Find the Debye length for a 1:1 salt at 5.0 mM and at 0.50 M, and comment on colloid stability.",
      h: "(a) The number ratio is Nᵢ. (b) X_n = 1/(1 − p), Đ = 1 + p. (c) κ⁻¹ = 0.304/√c nm.",
      s: ["(a) M̄n = (2×10 + 3×30 + 1×90)/6 = 200/6 = 33.3 kg mol⁻¹",
          "M̄w = (2×10² + 3×30² + 1×90²)/(2×10 + 3×30 + 1×90) = 11000/200 = 55.0 kg mol⁻¹,  Đ = 1.65",
          "(b) 1/(1 − p) = 200 → p = 0.995 (99.5%),  Đ = 1 + p = 1.995",
          "(c) 5.0 mM: κ⁻¹ = 0.304/√0.0050 = 4.3 nm;  0.50 M: κ⁻¹ = 0.43 nm",
          "With more salt the double layer is thinner, the electrostatic repulsion acts only at short range, the DLVO barrier drops and the colloid coagulates more easily"],
      a: "(a) 33.3, 55.0 kg mol⁻¹, Đ = 1.65 (b) p = 0.995, Đ = 1.995 (c) 4.3 nm, 0.43 nm" } },
  { w: 6, id: "W6-B",
    ko: { t: "농도–시간 데이터로 차수 정하기, Arrhenius", q: "A → 생성물 반응에서 다음 데이터를 얻었다(설명용 가상 데이터): t (s) = 0, 50, 100, 200, 400에서 [A] (M) = 0.0500, 0.0333, 0.0250, 0.0167, 0.0100. (a) 0차·1차·2차 중 어느 것인지 판별하고 k를 구하라. (b) 첫 번째와 두 번째 반감기를 구하라. (c) 다른 반응의 속도 상수가 25 °C에서 45 °C로 올릴 때 3.0배가 되었다. Ea를 구하라. (d) 298 K에서 촉매가 Ea를 10 kJ mol⁻¹ 낮추면 속도는 몇 배?",
      h: "(a) [A], ln[A], 1/[A] 중 무엇이 t에 대해 직선인지 본다. (b) 2차의 t½ = 1/(k[A])는 시작 농도에 따라 바뀐다.",
      s: ["(a) 1/[A] = 20.0, 30.0, 40.0, 60.0, 100: 50 s마다 10씩 늘어 t에 직선이다. ln[A] = −3.00, −3.40, −3.69, −4.09, −4.61은 직선이 아니다",
          "따라서 2차, 기울기 k = (100 − 20)/400 = 0.200 M⁻¹ s⁻¹",
          "(b) 첫 반감기 1/(k[A]₀) = 1/(0.200 × 0.0500) = 100 s (표에서 0.0500 → 0.0250)",
          "두 번째 반감기는 [A] = 0.0250에서 시작: 1/(0.200 × 0.0250) = 200 s (0.0250 → 0.0125). 반감기가 두 배로 느는 것이 2차의 지문",
          "(c) Ea = R ln(k₂/k₁)/(1/T₁ − 1/T₂) = 8.314 × ln3.0 / (1/298.15 − 1/318.15) = 43.3 kJ mol⁻¹",
          "(d) k_cat/k = e^{ΔEa/RT} = e^{10000/(8.314 × 298.15)} = e^{4.03} = 56.5배"],
      a: "(a) 2차, k = 0.200 M⁻¹ s⁻¹ (b) 100 s, 200 s (c) 43.3 kJ mol⁻¹ (d) 약 57배" },
    en: { t: "Order from concentration–time data; Arrhenius", q: "For A → products the following data were obtained (illustrative data): at t (s) = 0, 50, 100, 200, 400, [A] (M) = 0.0500, 0.0333, 0.0250, 0.0167, 0.0100. (a) Decide whether the reaction is zeroth, first or second order and find k. (b) Find the first and second half-lives. (c) The rate constant of another reaction triples between 25 °C and 45 °C. Find Ea. (d) At 298 K, by what factor does a catalyst that lowers Ea by 10 kJ mol⁻¹ speed up the reaction?",
      h: "(a) See which of [A], ln[A] and 1/[A] is linear in t. (b) The second-order t½ = 1/(k[A]) depends on the starting concentration.",
      s: ["(a) 1/[A] = 20.0, 30.0, 40.0, 60.0, 100: it rises by 10 every 50 s, linear in t. ln[A] = −3.00, −3.40, −3.69, −4.09, −4.61 is not linear",
          "So second order, with slope k = (100 − 20)/400 = 0.200 M⁻¹ s⁻¹",
          "(b) First half-life 1/(k[A]₀) = 1/(0.200 × 0.0500) = 100 s (0.0500 → 0.0250 in the table)",
          "The second starts at [A] = 0.0250: 1/(0.200 × 0.0250) = 200 s (0.0250 → 0.0125). Doubling half-lives are the fingerprint of second order",
          "(c) Ea = R ln(k₂/k₁)/(1/T₁ − 1/T₂) = 8.314 × ln3.0 / (1/298.15 − 1/318.15) = 43.3 kJ mol⁻¹",
          "(d) k_cat/k = e^{ΔEa/RT} = e^{10000/(8.314 × 298.15)} = e^{4.03} = 56.5 times"],
      a: "(a) second order, k = 0.200 M⁻¹ s⁻¹ (b) 100 s, 200 s (c) 43.3 kJ mol⁻¹ (d) about 57 times" } },
];

// ── 2025 midterm (original English statements; solutions re-typeset) ──
// s: solution lines; note: optional remark shown under the solution
export const PAST = [
  {
    head: "Problem 1 (15 points)",
    intro: "For the nth stationary state of the infinite square well (well width = a), we can use the 1D wave function ψₙ(x) (n = integer, > 0) as  ψₙ(x) = A sin(nπx/a),  A > 0.",
    parts: [
      { id: "1.1", pts: 1, q: "Using the normalization condition for the wave function, please find A.",
        s: ["⟨ψₙ|ψₙ⟩ = ∫₀ᵃ ψₙ*ψₙ dx = A² ∫₀ᵃ sin²(nπx/a) dx = A² · a/2 = 1",
            "∴ A = (2/a)^{1/2}"] },
      { id: "1.2", pts: 3, q: "Now, we would like to find the average position, ⟨x⟩, of the particle described by ψₙ. Please calculate ⟨x⟩.",
        s: ["⟨x⟩ = ∫₀ᵃ ψₙ* x ψₙ dx = (2/a) ∫₀ᵃ x sin²(nπx/a) dx",
            "= (2/a) [ x²/4 − (ax/4πn) sin(2nπx/a) − (a²/8π²n²) cos(2nπx/a) ]₀ᵃ",
            "= (2/a)(a²/4) = a/2"] },
      { id: "1.3", pts: 3, q: "Now, we would like to find the average momentum, ⟨p⟩, of the particle described by ψₙ. Please calculate ⟨p⟩.",
        s: ["⟨p⟩ = ∫₀ᵃ ψₙ* (−iℏ d/dx) ψₙ dx = −(2iℏnπ/a²) ∫₀ᵃ sin(nπx/a) cos(nπx/a) dx",
            "= −(iℏnπ/a²) ∫₀ᵃ sin(2nπx/a) dx = 0"] },
      { id: "1.4", pts: 3, q: "Now, we would like to find the average squared position, ⟨x²⟩, of the particle described by ψₙ. Please calculate ⟨x²⟩.",
        s: ["⟨x²⟩ = (2/a) ∫₀ᵃ x² sin²(nπx/a) dx",
            "= (2/a) [ x³/6 − (a x²/4πn − a³/8π³n³) sin(2nπx/a) − (a² x/4π²n²) cos(2nπx/a) ]₀ᵃ",
            "= a² (1/3 − 1/(2π²n²))"] },
      { id: "1.5", pts: 3, q: "Now, we would like to find the average squared momentum, ⟨p²⟩, of the particle described by ψₙ. Please calculate ⟨p²⟩.",
        s: ["⟨p²⟩ = ∫₀ᵃ ψₙ* (−ℏ² d²/dx²) ψₙ dx = (2ℏ²n²π²/a³) ∫₀ᵃ sin²(nπx/a) dx",
            "= (2ℏ²n²π²/a³)(a/2) = n²π²ℏ²/a²   (= 2mEₙ, as it must be)"] },
      { id: "1.6", pts: 2, q: "From the results you obtained from 1.2–1.5, please prove that the uncertainty principle holds for ψₙ(x). For this problem, you need to check the uncertainty principle for the case of n = 1.",
        s: ["σ_x = (⟨x²⟩ − ⟨x⟩²)^{1/2} = a (1/12 − 1/(2π²n²))^{1/2}",
            "σ_p = (⟨p²⟩ − ⟨p⟩²)^{1/2} = nπℏ/a",
            "σ_x σ_p = (ℏ/2) (n²π²/3 − 2)^{1/2}",
            "n = 1:  σ_x σ_p = (ℏ/2)(π²/3 − 2)^{1/2} = (ℏ/2) × 1.1357 > ℏ/2   Q.E.D."] },
    ],
  },
  {
    head: "Problem 2 (12 points)",
    intro: "You are a chemical engineer to develop some new material X. You found that you can use an auto-catalytic reaction with some chemical A such that  A + X → 2X  (rate constant k).",
    parts: [
      { id: "2.1", pts: 3, q: "Please derive the governing equation for the reaction rate of A and X. For this problem, you can use the initial condition of the reaction such that [A]₀ = A₀, [X]₀ = X₀. It would be convenient to use the reaction extent, x, such as [X] = [X]₀ + x.",
        s: ["d[A]/dt = −k[A][X],   d[X]/dt = k[A][X],   [A] = [A]₀ − x,   [X] = [X]₀ + x",
            "∴ d[A]/dt = −k([A]₀ − x)([X]₀ + x) = −k([A]₀ + [X]₀ − [X])[X]",
            "∴ d[X]/dt = k([A]₀ − x)([X]₀ + x) = k([A]₀ + [X]₀ − [X])[X]"],
        note: { ko: "x = [X] − [X]₀이므로 [A]₀ − x = [A]₀ + [X]₀ − [X]입니다(부호 주의).", en: "Since x = [X] − [X]₀, [A]₀ − x = [A]₀ + [X]₀ − [X] (watch the sign)." } },
      { id: "2.2", pts: 2, q: "For 2.1, please simplify the governing equation by assuming that [X]₀ ≈ 0.",
        s: ["d[A]/dt ≈ −k([A]₀ − [X])[X]",
            "d[X]/dt ≈ k([A]₀ − [X])[X]"] },
      { id: "2.3", pts: 3, q: "From the result you obtained from 2.2, please derive the time-dependent profile of the concentration of X.",
        s: ["d[X]/{([A]₀ − [X])[X]} = k dt  →  ∫ (1/[X] + 1/([A]₀ − [X])) d[X] = k[A]₀ ∫ dt",
            "∴ ln{[X]/([A]₀ − [X])} = k[A]₀ t + C,   C = ln{[X]₀/([A]₀ − [X]₀)}",
            "∴ [X](t) = [A]₀ / {1 + (([A]₀ − [X]₀)/[X]₀) exp(−k[A]₀ t)}"],
        note: { ko: "[X]₀가 작아도 0이면 반응이 시작되지 않으므로 적분 상수에는 [X]₀가 남습니다. 결과는 S자(로지스틱) 곡선입니다.", en: "Even if [X]₀ is small it cannot be exactly zero, or the reaction never starts, so it survives in the integration constant. The result is an S-shaped (logistic) curve." } },
      { id: "2.4", pts: 3, q: "Some of your colleagues reported experimental data for [X](t) in a linear form of ln{[X]/([A]₀ − [X])} (y-axis) vs. time (x-axis). They reported the slope of the linearity is 0.6102 min⁻¹. Given a condition of [A]₀ = 10 mM, please calculate k in a unit of M⁻¹ s⁻¹.",
        s: ["slope = k[A]₀ = 0.6102 min⁻¹,   [A]₀ = 1.0×10⁻² M",
            "∴ k = 0.6102 min⁻¹ × (1 min/60 s) × 1/(1.0×10⁻² M) = 1.017 M⁻¹ s⁻¹"] },
      { id: "2.5", pts: 1, q: "Your colleague also reported the y-intercept in the linear form of ln{[X]/([A]₀ − [X])} (y-axis) vs. time (x-axis) of −1. Please evaluate [X]₀. Can you confirm the validity of the initial assumption such that [X]₀ ≈ 0?",
        s: ["y-intercept = ln{[X]₀/([A]₀ − [X]₀)} = −1  →  [X]₀ = e⁻¹([A]₀ − [X]₀)",
            "∴ [X]₀ = e⁻¹[A]₀/(1 + e⁻¹) = 2.689×10⁻³ M",
            "[X]₀ ≈ 0.27[A]₀, so the initial assumption is not valid; the more exact form of 2.1 is needed."] },
    ],
  },
  {
    head: "Problem 3 (8 points)",
    intro: "For the Michaelis–Menten reaction model to describe an enzymatic reaction,  E + S ⇌ ES → E + P  (k_f, k_r; k_p), we would like to obtain a more exact form for the description of the substrate concentration [S] given the total concentration of the enzyme, [E]_T, is fixed. For this problem, you can assume QSSA for [ES].",
    parts: [
      { id: "3.1", pts: 3, q: "Please derive the time-dependent profile of the concentration of S given the initial concentration of [S]₀. For this problem, you don't need to provide a closed form for the profile of [S].",
        s: ["d[S]/dt = −k_f[E][S] + k_r[ES]",
            "QSSA → d[S]/dt = −V_max[S]/(K_m + [S]),   K_m = (k_r + k_p)/k_f,   V_max = k_p[E]_T",
            "∴ {(K_m + [S])/[S]} d[S] = −V_max dt",
            "∴ K_m ln([S]/[S]₀) + [S] − [S]₀ = −V_max t"] },
      { id: "3.2", pts: 3, q: "Your colleague suggests that you can make some approximation for the solution you obtained in 3.1 for the early stage of the reaction, where there is negligible consumption of [S]. Please derive the approximated solution for [S]. For this, it would be convenient to set [S]/[S]₀ = 1 − x.",
        s: ["Early stage: [S]/[S]₀ = 1 − x with x ≪ 1, so ln(1 − x) ≈ −x and [S] − [S]₀ = −[S]₀x",
            "→ −K_m x − [S]₀ x = −V_max t",
            "∴ x = V_max t/(K_m + [S]₀)",
            "∴ [S] = [S]₀ {1 − V_max t/(K_m + [S]₀)}   (linear decay at the initial rate V_max[S]₀/(K_m + [S]₀))"],
        note: { ko: "확인: t = 0에서 [S] = [S]₀이고, 기울기 d[S]/dt = −V_max[S]₀/(K_m + [S]₀)는 Michaelis–Menten 초기 속도와 같습니다.", en: "Check: [S] = [S]₀ at t = 0, and the slope d[S]/dt = −V_max[S]₀/(K_m + [S]₀) equals the Michaelis–Menten initial rate." } },
      { id: "3.3", pts: 2, q: "After enough time, you would be able to obtain another approximated form by considering that [S] ≪ [S]₀. Please derive the approximated solution for [S] in this case. Given a condition of [S]₀ = 10K_m and V_max = K_m/τ, where τ denotes the characteristic time scale for the reaction, we can safely assume that [S] ≪ [S]₀ if [S] ≤ 0.01[S]₀. How long does it take for this assumption to make sense? Please provide the minimum time in the unit of τ.",
        s: ["Late stage: [S] ≪ [S]₀  →  K_m ln([S]/[S]₀) − [S]₀ ≈ −V_max t",
            "∴ [S] ≈ [S]₀ exp{([S]₀ − V_max t)/K_m}",
            "[S] ≤ 10⁻²[S]₀ with [S]₀ = 10K_m, V_max = K_m/τ:  10⁻² ≥ exp(10 − t/τ)",
            "→ −4.6052 ≥ 10 − t/τ   ∴ t ≥ 14.6 τ"] },
    ],
  },
];

// ── constants and pitfalls ──────────────────────────────────
export const CONSTANTS = [
  ["h", "6.626×10⁻³⁴ J s"], ["ℏ = h/2π", "1.0546×10⁻³⁴ J s"], ["c", "2.998×10⁸ m s⁻¹"],
  ["k_B", "1.381×10⁻²³ J K⁻¹"], ["N_A", "6.022×10²³ mol⁻¹"], ["R = N_A k_B", "8.314 J K⁻¹ mol⁻¹"],
  ["e", "1.602×10⁻¹⁹ C"], ["m_e", "9.109×10⁻³¹ kg"], ["ε₀", "8.854×10⁻¹² C² J⁻¹ m⁻¹"],
  ["μ_B", "9.274×10⁻²⁴ J T⁻¹"], ["1 u", "1.6605×10⁻²⁷ kg"], ["1 eV", "1.602×10⁻¹⁹ J = 96.49 kJ mol⁻¹"],
  ["hc", "1239.84 eV·nm"], ["R_H", "109 677 cm⁻¹"], ["σ (Stefan–Boltzmann)", "5.670×10⁻⁸ W m⁻² K⁻⁴"],
  ["Wien b", "2.898×10⁻³ m K"], ["1 D", "3.336×10⁻³⁰ C m"], ["k_BT (298 K)", "4.11×10⁻²¹ J = 25.7 meV"],
];

export const PITFALLS = [
  { ko: ["ln과 log₁₀", "적분 속도식과 Arrhenius 식은 자연로그입니다. 문제에 'log'라고만 쓰여 있으면 어느 쪽인지 먼저 확인하세요. 작년 시험의 'log'는 ln이었습니다."],
    en: ["ln vs log₁₀", "Integrated rate laws and the Arrhenius equation use natural logs. If a problem just says 'log', check which is meant first; on last year's exam 'log' meant ln."] },
  { ko: ["h와 ℏ", "상자의 Eₙ = n²h²/8mL²와 n²π²ℏ²/2mL²는 같은 식입니다. 한 식 안에서 h와 ℏ를 섞으면 2π 배수 오류가 납니다."],
    en: ["h vs ℏ", "Eₙ = n²h²/8mL² and n²π²ℏ²/2mL² are the same formula. Mixing h and ℏ in one expression gives factor-of-2π errors."] },
  { ko: ["분자 하나 vs 1 mol", "k_B ↔ R, m ↔ M. 속력 식 √(3RT/M)의 M은 kg mol⁻¹입니다(32 g mol⁻¹ → 0.032)."],
    en: ["Per molecule vs per mole", "k_B ↔ R and m ↔ M. In √(3RT/M), M is in kg mol⁻¹ (32 g mol⁻¹ → 0.032)."] },
  { ko: ["파수 단위", "ν̃ = ω/2πc를 cm⁻¹로 얻으려면 c = 2.998×10¹⁰ cm s⁻¹를 넣습니다."],
    en: ["Wavenumber units", "To get ν̃ = ω/2πc in cm⁻¹, insert c = 2.998×10¹⁰ cm s⁻¹."] },
  { ko: ["환산질량", "이원자 진동의 ω = √(k/μ)에는 원자 하나의 질량이 아니라 μ = m₁m₂/(m₁ + m₂)를 씁니다."],
    en: ["Reduced mass", "For a diatomic vibration ω = √(k/μ) uses μ = m₁m₂/(m₁ + m₂), not the mass of one atom."] },
  { ko: ["전자 채우기", "자유 전자 모형에서 한 준위에 전자 2개가 들어갑니다. N개 전자의 HOMO는 n = N/2입니다."],
    en: ["Filling levels", "In the free-electron model each level holds two electrons, so the HOMO of N electrons is n = N/2."] },
  { ko: ["축퇴도와 스핀", "수소의 n² 축퇴도는 스핀을 뺀 값입니다. 전자 수(주기율표)를 셀 때는 2n²."],
    en: ["Degeneracy and spin", "Hydrogen's n² degeneracy excludes spin; count 2n² when filling electrons (periodic table)."] },
  { ko: ["속도 상수의 단위", "0차 M s⁻¹, 1차 s⁻¹, 2차 M⁻¹ s⁻¹. 분 단위 데이터는 마지막에 60으로 나누는 것을 잊지 마세요."],
    en: ["Units of rate constants", "Zeroth order M s⁻¹, first s⁻¹, second M⁻¹ s⁻¹. With data in minutes, remember to divide by 60 at the end."] },
  { ko: ["온도는 K", "Arrhenius와 Boltzmann 인자에는 절대온도를 넣습니다. 25 °C → 298.15 K."],
    en: ["Temperatures in kelvin", "Arrhenius and Boltzmann factors need absolute temperature: 25 °C → 298.15 K."] },
  { ko: ["Laplace 압력의 면 수", "액체 속 기포는 면이 하나라 2σ/r, 비눗방울 막은 두 면이라 4σ/r입니다."],
    en: ["Number of surfaces in Laplace pressure", "A bubble inside a liquid has one surface (2σ/r); a soap bubble film has two (4σ/r)."] },
  { ko: ["근사의 조건", "Taylor 전개(ln(1 − x) ≈ −x), 넓은 장벽 근사(κa ≫ 1), 작은 진폭(sin θ ≈ θ)을 쓸 때는 조건이 맞는지 한 줄로 확인하세요."],
    en: ["Conditions of approximations", "When using a Taylor expansion (ln(1 − x) ≈ −x), the wide-barrier limit (κa ≫ 1) or small amplitude (sin θ ≈ θ), check in one line that the condition holds."] },
  { ko: ["유효숫자와 단위", "마지막 답은 주어진 데이터의 유효숫자(보통 3자리)와 단위를 붙여 씁니다. nm·pm·Å 변환을 다시 확인하세요."],
    en: ["Significant figures and units", "Give final answers with the data's significant figures (usually three) and units; double-check nm, pm and Å conversions."] },
];
